### ISSUE TITLE
Launcher wont launch - DeprecationWarning - panic: runtime error - [Ubuntu Jammy 22.04]

### ISSUE THREAD

**Issue by ghost** [Alderon-Games/alderongames-launcher-bugs#109]
Hey Alderon devs. 
I moved to Ubuntu MATE 22.04 and now I have a dino withdrawl. 
The launcher will not open. AppImage or snap. Some errors seem familiar, as I've seen them on Debian but I don't remember how I 'fixed' it.  

running the .AppImage through terminal shows this:

./AlderonGamesLauncher-1.1.77.AppImage
```
OSVersionCheck OSVersion { type: 'Linux', version: '5.15.0-52-generic' }
OSVersionCheck ProductVersion { type: 'Linux', version: '5.15.0-52-generic' }
[20:11:01.020:app:info] Logger Initiated
[20:11:01.021:app:info] Pre Global Logger
[20:11:01.021:app:info] Post Global Logger
(node:13122) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `alderon-games-launcher --trace-deprecation ...` to show where the warning was created)
(node:13122) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:13122) DeprecationWarning: file property is deprecated and will be removed in v5.
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
```

running the snap outputs this: 
snap --launch ./AlderonGamesLauncher-1.1.77.snap 
(I dont even know if this is the right command, please forgive me)
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x563979cee76e]

goroutine 1 [running]:
main.main.func1()
	/build/snapd-2F68MV/snapd-2.57.5+22.04/cmd/snap/main.go:492 +0x5c
panic({0x56397a0bb220, 0x56397a5b4b10})
	/usr/lib/go-1.18/src/runtime/panic.go:838 +0x207
main.run()
	/build/snapd-2F68MV/snapd-2.57.5+22.04/cmd/snap/main.go:559 +0x2ee
main.main()
	/build/snapd-2F68MV/snapd-2.57.5+22.04/cmd/snap/main.go:497 +0x47e
```

System info: 
`glxinfo | grep "renderer string"`
OpenGL renderer string: AMD Radeon RX 6600 (dimgrey_cavefish, LLVM 13.0.1, DRM 3.42, 5.15.0-52-generic)

`glxinfo | grep "OpenGL version"`
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.5

`lspci -nnk | grep -i -EA3 "3d|display|vga"`

03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c7)
	Subsystem: Sapphire Technology Limited Navi 23 [Radeon RX 6600/6600 XT/6600M] [1da2:e447]
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

Thanks for your help and for all the hard work.

**Comment by ghost** [comment]
OK sorry about my ignorance of snap usage in the past. 
I'm just here to update that the bug persists in version 1.1.79

## This was the way I installed the snap: 
`snap install AlderonGamesLauncher-1.1.79.snap --dangerous`

leaving out --dangerous lead to this output:
`error: cannot find signatures with metadata for snap "AlderonGamesLauncher-1.1.79.snap"`

The launcher seemed like it installed but then when I ran it there was the similar error: 
`snap run alderon-games-launcher`

```
OSVersionCheck OSVersion { type: 'Linux', version: '5.15.0-58-generic' }
OSVersionCheck ProductVersion { type: 'Linux', version: '5.15.0-58-generic' }
[09:55:13.773:app:info] Logger Initiated
[09:55:13.775:app:info] Pre Global Logger
[09:55:13.775:app:info] Post Global Logger
(node:8570) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `alderon-games-launcher --trace-deprecation ...` to show where the warning was created)
(node:8570) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:8570) DeprecationWarning: file property is deprecated and will be removed in v5.
Failed to generate minidump.Segmentation fault (core dumped)
```
---

### Here is with the AppImage:
`./AlderonGamesLauncher-1.1.79.AppImage `

```
OSVersionCheck OSVersion { type: 'Linux', version: '5.15.0-58-generic' }
OSVersionCheck ProductVersion { type: 'Linux', version: '5.15.0-58-generic' }
[09:58:50.343:app:info] Logger Initiated
[09:58:50.344:app:info] Pre Global Logger
[09:58:50.344:app:info] Post Global Logger
(node:8956) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `alderon-games-launcher --trace-deprecation ...` to show where the warning was created)
(node:8956) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:8956) DeprecationWarning: file property is deprecated and will be removed in v5.
```

Same hardware, everything vital to running is from Ubuntu repos.
I'm able to repeat this error on several Ubuntu and Debian machines.
Much Love everyone, thanks for your work and I hope this helps.

**Comment by ghost** [comment]
Just wanted to note, I reinstalled Debian 11.5 MATE on one of my machines and it ran the AppImage and installed the game no problem. The same machine was running Ubuntu 20 & 22 for past year or more and has been unable to open launcher until now.  Something with Ubuntu prevented the launcher from working. I have this Debian machine to test now (not the one in above posts, but similar hardware). 
Plus I finally get to play.
