### ISSUE TITLE
Launcher .AppImage not working (Linux)

### ISSUE THREAD

**Issue by DraconianDeath** [Alderon-Games/alderongames-launcher-bugs#83]
## Expected Behavior
Cllicking AlderonGamesLauncher-1.1.59.AppImage after it's made executable should open the launcher.
## Current Behavior
Clicking the .AppImage seemingly doesn't do anything and I didn't notice any related processes in the Task Manager that would suggest it had been running in the background. Trying to launch it in the terminal doesn't offer a lot more info. Snap also didn't work but that might have been due to user error (I haven't used it before).
## Reproduction Steps
N/A

## Evidence
![241784130_1083979602138454_8329555136751987469_n](https://user-images.githubusercontent.com/55933398/133118971-f85e6e23-1cad-4ea8-a57e-a81f0c489eee.jpg)

## Crash Logs
N/A

## Build Information

**Game Version:** N/A (last time I played the demo on my PC was in 2019 and the version was 0.0.0.3979)
**Launcher Version:** 1.1.59

**Operating System:**

**System:**    Host: Megi-PC Kernel: 5.4.0-81-generic x86_64 bits: 64 gcc: 7.5.0
           Desktop: N/A Distro: Peppermint Ten
**Machine:**   Device: desktop Mobo: MSI model: H110M PRO-D (MS-7996) v: 1.0 serial: N/A
           UEFI [Legacy]: American Megatrends v: 2.50 date: 02/23/2016
**CPU:**       Quad core Intel Core i5-6400 (-MCP-)
           arch: Skylake-S rev.3 cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 21599
           clock speeds: max: 3300 MHz 1: 800 MHz 2: 800 MHz 3: 800 MHz 4: 800 MHz
**Graphics:**  Card: NVIDIA GP106 [GeForce GTX 1060 6GB] bus-ID: 01:00.0
           Display Server: x11 (X.Org 1.20.8 )
           drivers: nvidia (unloaded: modesetting,fbdev,vesa,nouveau)
           Resolution: 1920x1080@239.76hz
           OpenGL: renderer: GeForce GTX 1060 6GB/PCIe/SSE2
           version: 4.6.0 NVIDIA 460.91.03 Direct Render: Yes
**Audio:**     Card-1 Intel 100 Series/C230 Series Family HD Audio Controller
           driver: snd_hda_intel bus-ID: 00:1f.3
           Card-2 NVIDIA GP106 High Def. Audio Controller
           driver: snd_hda_intel bus-ID: 01:00.1
           Sound: Advanced Linux Sound Architecture v: k5.4.0-81-generic
**Network:**   Card: Realtek RTL8111/8168/8411 PCIE Gigabit Ethernet Controller
           driver: r8169 port: d000 bus-ID: 02:00.0
           IF: enp2s0 state: down mac: <filter>
**Drives:**    HDD Total Size: 1360.3GB (46.0% used)
           ID-1: /dev/sdb model: TOSHIBA_DT01ACA1 size: 1000.2GB
           ID-2: /dev/sda model: R3SL240G size: 240.1GB
           ID-3: /dev/sdc model: SanDisk_SDSSDA12 size: 120.0GB
**Partition:** ID-1: / size: 110G used: 44G (43%) fs: ext4 dev: /dev/sdc1
**RAID:**      No RAID devices: /proc/mdstat, md_mod kernel module present
**Sensors:**   System Temperatures: cpu: 33.0C mobo: N/A gpu: 0.0:39C
           Fan Speeds (in rpm): cpu: N/A
**Info:**      Processes: 228 Uptime: 37 min Memory: 1047.1/7925.2MB
           Init: systemd runlevel: 5 Gcc sys: 7.5.0
           Client: Shell (bash 4.4.201) inxi: 2.3.56

**Alderon Games ID:** 110-013-601

**Comment by alexsola** [comment]
I have similar problem both with the `snap` and the `AppImage` versions:
```
 Failed to get crash dump id. 
 Report Id:  b203184f-9026-48 
              /home/user/Games/alderon-games-launcher/AlderonGamesLauncher.sh: line 2: 11297 Segmentation fault      ./AlderonGamesLauncher-*.AppImage --no-sandbox
Monitored process exited.
Initial process has exited (return code: 35584)
All processes have quit
Exit with return code 35584
Started initial process 11330 from /home/user/Games/alderon-games-launcher/AlderonGamesLauncher.sh
Start monitoring process.
OSVersionCheck OSVersion { type: 'Linux', version: '5.7.0-0.bpo.2-amd64' }
OSVersionCheck ProductVersion { type: 'Linux', version: '5.7.0-0.bpo.2-amd64' }
[14:01:58.147:app:info] Logger Initiated
[14:01:58.148:app:info] Pre Global Logger
[14:01:58.149:app:info] Post Global Logger
(node:11331) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `alderon-games-launcher --trace-deprecation ...` to show where the warning was created)
(node:11331) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:11331) DeprecationWarning: file property is deprecated and will be removed in v5.
--2022-04-24 14:01:58--  https://o34825.ingest.sentry.io/api/5509509/minidump/?sentry_key=373d9a6906d6421b9dbebc16357dd61f
Resolving o34825.ingest.sentry.io (o34825.ingest.sentry.io)... 34.120.195.249
Connecting to o34825.ingest.sentry.io (o34825.ingest.sentry.io)|34.120.195.249|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36 [text/plain]
Saving to: ‘/dev/fd/4’

     0K                                       
  Failed to get crash dump id. 
```
I get a segmentation fault and the inability of the launcher to write a dump. The output above is for version 1.1.69, same happens with version 1.1.68.

**Comment by ghost** [comment]
Running AppImage outputs this:

```
OSVersionCheck OSVersion { type: 'Linux', version: '5.15.0-52-generic' }
OSVersionCheck ProductVersion { type: 'Linux', version: '5.15.0-52-generic' }
[22:16:06.760:app:info] Logger Initiated
[22:16:06.761:app:info] Pre Global Logger
[22:16:06.761:app:info] Post Global Logger
(node:4504) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `alderon-games-launcher --trace-deprecation ...` to show where the warning was created)
(node:4504) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:4504) DeprecationWarning: file property is deprecated and will be removed in v5.
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
```



Running snap in terminal outputs this: 

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55d00b6dc76e]

goroutine 1 [running]:
main.main.func1()
	/build/snapd-2F68MV/snapd-2.57.5+22.04/cmd/snap/main.go:492 +0x5c
panic({0x55d00baa9220, 0x55d00bfa2b10})

/usr/lib/go-1.18/src/runtime/panic.go:838 +0x207
 main.run()
/build/snapd-2F68MV/snapd-2.57.5+22.04/cmd/snap/main.go:559 +0x2ee
main.main()
/build/snapd-2F68MV/snapd-2.57.5+22.04/cmd/snap/main.go:497 +0x47e
```
